services:
  - type: web
    name: shopify-store
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Eshop.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: shopify-store.onrender.com
